FROM alpine
RUN apk add --no-cache curl wget busybox-extras netcat-openbsd python py-pip
RUN pip install -trusted-host pypi.org --trusted-host files.pythonhosted.org awscli 
RUN apk --purge -v del py-pip
CMD tail -f /dev/null